# Generated by Django 5.2.8 on 2025-12-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('intensity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_burn_30min', models.IntegerField(blank=True, null=True)),
                ('target_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_age', models.IntegerField(default=12)),
                ('max_age', models.IntegerField(default=80)),
                ('contra_hypertension', models.BooleanField(default=False)),
                ('contra_heart_disease', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contra_hypertension', models.BooleanField(default=False)),
                ('contra_diabetes', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('suitable_for', models.CharField(default='trua,toi', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserExercisePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(blank=True, choices=[(True, 'Like'), (False, 'Dislike')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.exercise')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_preferences', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.food')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='accounts.account')),
            ],
        ),
    ]
