# Generated by Django 5.2.8 on 2025-12-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tdee', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.SmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.SmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.SmallIntegerField(blank=True, null=True)),
                ('activity_level', models.SmallIntegerField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('goal', models.SmallIntegerField(blank=True, null=True)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('exercise', 'Exercise'), ('food', 'Food')], max_length=10, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_trackings', to='accounts.account')),
                ('weekly_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='analysis.weeklyplans')),
            ],
        ),
    ]
