# Generated by Django 5.2.8 on 2025-12-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantracking',
            name='instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
