# Generated by Django 5.2.8 on 2025-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_plantracking_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='daily_burn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='daily_calo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
